services:
  manager:
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    init: true
    ports:
      - ${MANAGER_PORT}:80
    environment:
      - RUST_LOG=${LOG}

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    init: true
    environment:
      - RUST_LOG=${LOG}
    deploy:
      replicas: ${WORKERS}
    restart: unless-stopped
    depends_on:
      - manager
